#!/bin/bash

EMACS='/Applications/Emacs.app'
# You'll probably have to change this
EMACS_CLIENT='/usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.1/bin/emacsclient'

DEFAULT_EVAL='(switch-to-buffer "*scratch*")'
DEFAULT_ARGS="-e"
NO_WAIT='-n'

function run_client(){
    if [ $# -ne 0 ]
    then
        ${EMACS_CLIENT} ${NO_WAIT} $@
    else
        ${EMACS_CLIENT} ${NO_WAIT} ${DEFAULT_ARGS} "${DEFAULT_EVAL}" &> /dev/null
    fi
}

if pgrep Emacs &> /dev/null
then
    run_client $*
else
    echo "Emacs server is starting..."
    open -a ${EMACS}

    until run_client $* &> /dev/null;[ $? -eq 0 ]
    do
        sleep 1
    done
fi
