#!/bin/sh
# Usage:
# Install icdiff
# Add the following to ~/.gitconfig:
#
# [diff]
#		external = gwu_external_diff
#
# $ git diff
#
# See: https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

[ $# -eq 7 ] && icdiff -N "$2" "$5"
