#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
# -cmo: include cached, modified, and other (untracked) files
# --exclude-standard: respect local and global gitignores
git ls-files -cmo --exclude-standard | \
  ctags --tag-relative=yes -L- -f"$dir/$$.tags" --languages=-javascript,sql
mv "$dir/$$.tags" "$dir/tags"
